name: Dependabot

on:
  pull_request:

jobs:
  generate:
    if: ${{ github.actor == 'dependabot[bot]' }}
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3
        with:
          ref: ${{ github.head_ref }}
          submodules: "true"
          token: ${{ secrets.APPARITOR_GITHUB_TOKEN }}

      - name: Generate
        run: make generate

      - name: Commit
        uses: devops-infra/action-commit-push@8a2d9d73c3f506468129be2e4409e60dbed70357
        with:
          github_token: ${{ secrets.APPARITOR_GITHUB_TOKEN }}
          commit_message: "dependabot: generate"

  build:
    if: ${{ github.actor == 'dependabot[bot]' }}
    name: Build
    needs: generate
    uses: ./.github/workflows/reusable-build.yaml
    with:
      ref: ${{ github.head_ref }}
